[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm --prefix backend install",
  "npm --prefix frontend install"
]

[phases.build]
cmds = ["npm --prefix frontend run build"]

[start]
cmd = "npm --prefix backend install && npm --prefix backend start"

